APFPlanner:
  # offset of transform from world(x,y) to grid map(x,y)
  convert_offset: 0.0

  # next point distance
  p_window: 0.5

  # goal reached tolerance
  p_precision: 0.2
  o_precision: 0.5

  # linear velocity
  max_v: 0.5
  min_v: 0.0
  max_v_inc: 0.5

  # angular velocity
  max_w: 1.57
  min_w: 0.0
  max_w_inc: 1.57

  s_window: 5  # trajectory smoothing window time

  zeta: 1.0     # scale factor of attractive force
  eta: 1.0   # scale factor of repulsive force

  cost_ub: 254  # the upper bound of costmap used to calculate potential field
  cost_lb: 0    # the lower bound of costmap used to calculate potential field

  # the costmap inflation radius of obstacles
  # this parameter should be consistent with that in sim_env/config/costmap/xxx_costmap_params.yaml
  inflation_radius: 1.0

  base_frame: base_link
  map_frame: map