EvolutionaryPlanner:
  # offset of transform from world(x,y) to grid map(x,y)
  convert_offset: 0.0
  # error tolerance
  default_tolerance: 0.0
  # whether outline the map or not
  outline_map: true
  # obstacle inflation factor
  obstacle_factor: 0.39

  ## Ant Colony Optimization(ACO) planner 
  # number of ants
  n_ants: 50
  # pheromone weight coefficient
  alpha: 1.0
  # heuristic factor weight coefficient
  beta: 8.0
  # evaporation coefficient
  rho: 0.1
  # pheromone gain
  Q: 1.0
  # maximum iterations
  max_iter: 30

  ## Ant Colony Optimization(PSO) planner 
  # number of particles
  n_particles: 50
  # number of inherited particles (Note: Need to be less than parameter n_ Particles)
  n_inherited: 20
  # number of position points contained in each particle
  pointNum: 5
  # The maximum velocity of particle motion
  max_speed: 40
  # inertia weight
  w_inertial: 1.0
  # social weight
  w_social: 2.0
  # cognitive weight
  w_cognitive: 1.2
  # Set the generation mode for the initial position points of the particle swarm
  # 1: Randomly generate initial positions of particle swarm within the map range
  # 2: Randomly generate initial particle swarm positions within the circular area of the starting and target points
  initposmode: 2
  # Whether to publish particles
  pub_particles: false
  # maximum iterations
  pso_max_iter: 5